#!/bin/sh -e

##########################################################################
#   Script description:
#       Count unique sequences at 5' end of each read
#       
#   History:
#   Date        Name        Modification
#   2019-09-18  Jason Wayne BaconBegin
##########################################################################

usage()
{
    printf "Usage: $0 file [file ...]\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# -lt 1 ]; then
    usage
fi

for file in "$@"; do
    printf "$file:\n"
    printf "1-10:\t"
    zgrep -v -E '^\+|^F|^@|:|,' "$file" | cut -c 1-10 | sort | uniq | wc -l
    printf "41-50:\t"
    zgrep -v -E '^\+|^F|^@|:|,' "$file" | cut -c 41-50 | sort | uniq | wc -l
done

