#!/bin/sh -e

##########################################################################
#   Script description:
#       Organize files and create directories needed for analysis
#
#       Link raw files to standardized names for that clearly describe
#       conditions and replicates, and are easily parsed by subsequent
#       scripts.
#
#       Researchers involved in sample-prep generally don't think about
#       how filename conventions impact bioinformatics analysis, so this
#       simple step can avoid confusion throughout the pipeline.  In
#       addition, linking this way can correct for sample mixups, etc.
#
#       Use links to preserve the original files and document the mapping.
#       
#   History:
#   Date        Name        Modification
#   2021-09-25  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi

mkdir -p Data Logs
for stage in 1-trim 2-qc 3-reference 4-kallisto-index 5-kallisto-quant \
    6-merge-bams 7-sleuth-DE;do
    mkdir -p Data/$stage Logs/$stage
done

# CE1A_S1_L002-R1.fastq.xz
cd Data
rm -rf Raw-renamed
mkdir -p Raw-renamed
cd Raw-renamed
for rep in 1 2 3; do
    for time in A B C; do
	numeric_time=$(echo $time | tr "ABC" "123")
	for read in 1 2; do
	    orig=$(ls ../../../Raw/190822_AHFN3KDRXX-Lane2/CE${rep}${time}_*_L002_R${read}_001.fastq.xz)
	    sample=$(echo $orig | awk -F '_' '{ print $3 }' | sed -e 's|S|sample|')
	    ln -s $orig \
		chondro-$sample-rep${rep}-time${numeric_time}-R${read}.fastq.xz
	    orig=$(ls ../../../Raw/190822_AHFN3KDRXX-Lane2/NE${rep}${time}_*_L002_R${read}_001.fastq.xz)
	    sample=$(echo $orig | awk -F '_' '{ print $3 }' | sed -e 's|S|sample|')
	    ln -s $orig \
		neuro-$sample-rep${rep}-time${numeric_time}-R${read}.fastq.xz
	done
    done
done
ls -l
