#!/bin/sh -e

##########################################################################
#   Description:
#       Run differential analysis on hisat2 alignments.
#
#       All necessary tools are assumed to be in PATH.  If this is not
#       the case, add whatever code is needed here to gain access.
#       (Adding such code to your .bashrc or other startup script is
#       generally a bad idea since it's too complicated to support
#       every program with one environment.)
#       
#   History:
#   Date        Name        Modification
#   2021-11-26  Jason Bacon Begin
##########################################################################

##########################################################################
#   Run differential analysis on hisat2 alignments
##########################################################################

hostname
