#!/bin/sh -e

if hostname | fgrep peregrine; then
    printf "Duh.\n"
    exit 1
fi

# Sync output files, which are not (and should not be) added to the repo
rna_dirs="1-trim 2-qc 3-kallisto-index 4-kallisto-quant-0.46.1 5-merge-bams 6-diff-anal"
atac_dirs="1-trim 2-qc 3-bwa-index 4-bwa-mem 5-qc-sam 6-remove-duplicates 7-macs-peaklets 8-merge-bams 9-process-peaks 10-diff-anal"

printf "RNA-Seq...\n"
for file in $rna_dirs; do
    list="$list peregrine.hpc.uwm.edu:Data/CNC-EMDiff/RNA-Seq/$file"
done
rsync -av --size-only "$@" $list RNA-Seq

printf "ATAC-Seq...\n"
list=""
for file in $atac_dirs; do
    list="$list peregrine.hpc.uwm.edu:Data/CNC-EMDiff/ATAC-Seq/$file"
done
rsync -av --size-only "$@" $list ATAC-Seq

