#!/bin/sh -e

cd Data
awk -F , '$1 != "" && $1 !~ "Commonly up" { print $1 }' \
    genes-common.csv > genes-common-up.txt
awk -F , '$4 != "" && $4 !~ "Commonly down" { print $4 }' \
    genes-common.csv > genes-common-down.txt
awk '$1 != "" && $1 !~ "Chondro-specific" { print $1 }' \
    genes-chondro.csv > genes-chondro.txt
awk '$1 != "" && $1 !~ "Neuro-specific" { print $1 }' \
    genes-neuro.csv > genes-neuro.txt

for file in neuro*.csv chondro*.csv; do
    echo $file
    tsv=${file%.csv}.tsv
    awk -F , -f ../fill.awk $file | tr -s ', ' '\t-' \
	| cut -f 1,2,3,8,9,13,15,17,19 > $tsv
done
