#!/bin/sh -e

gff=Mus_musculus.GRCm38.98.chr.gff3.gz
if [ ! -e $gff ]; then
    ftp://ftp.ensembl.org/pub/release-98/gff3/mus_musculus/$gff
fi

gzcat $gff | head -20 | tail -19 | awk '{ printf("%s\t%s\n", $2, $4); }' \
    | sort -n > chromosome-sizes.tsv
