#!/bin/sh -e

if which cluster-run; then
    cluster_run=cluster-run
    node_spec=compute
else
    cluster_run='sh -c'
fi

case $(uname) in
FreeBSD)
    # Install ports on all compute nodes
    # DiffBind deps: librsvg2 v8 pkgconf
    printf "Root "
    su -m root -c "$cluster_run 'pkg install -y py37-cutadapt fastqc py37-multiqc bwa samtools py37-macs2 bedtools R librsvg2 pkgconf' $node_spec"

    # v8 javascript engine API changes frequently and FreeBSD ports version
    # is incompatible with DiffBind
    printf "Root "
    # su -m root -c "$cluster_run 'wip-reinstall-port -u -r v8' $node_spec"
    ;;

*)
    printf "$0: $(uname) is not yet supported.\n"
    exit 1
    ;;

esac

# Install R packages into a shared location
# Use a compute node to install if on a cluster
if which srun; then
    srun='srun --mem=500'
fi
read -p 'R prefix? [/sharedapps/R] ' prefix
if [ 0$prefix = 0 ]; then
    prefix='/sharedapps/R'
fi
read -p 'CRAN URL? [https://mirror.las.iastate.edu/CRAN/]' url
if [ 0$url = 0 ]; then
    url='https://mirror.las.iastate.edu/CRAN/'
fi
mkdir -p $prefix
$srun Utils/install-R-packages $prefix $url
