#!/bin/sh -e

if which cluster-run; then
    cluster_run=cluster-run
    node_spec=compute
else
    cluster_run='sh -c'
fi

case $(uname) in
FreeBSD)
    py_prefix=py38
    # Install ports on all compute nodes
    # DiffBind deps: librsvg2 pkgconf
    printf "Root "
    su -m root -c "$cluster_run 'pkg install -y $py_prefix-cutadapt fastqc \
	$py_prefix-multiqc bwa samtools $py_prefix-macs2 bedtools R \
	librsvg2 pkgconf' $node_spec"
    ;;

*)
    printf "$0: $(uname) is not yet supported.\n"
    exit 1
    ;;

esac

# Install R packages into a shared location
# Use a compute node to install if on a cluster
if which srun; then
    srun='srun --mem=500'
fi
read -p 'R prefix? [/sharedapps/R] ' prefix
if [ 0$prefix = 0 ]; then
    prefix='/sharedapps/R'
fi
read -p 'CRAN URL? [https://mirror.las.iastate.edu/CRAN/]' url
if [ 0$url = 0 ]; then
    url='https://mirror.las.iastate.edu/CRAN/'
fi
mkdir -p $prefix
$srun Utils/install-R-packages $prefix $url
