#!/bin/sh -e

##########################################################################
#   Script description:
#       Count unique differentially accessible peaks based on DESeq2
#       results.
#       
#   History:
#   Date        Name        Modification
#   2020-06-10  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi

for cell_type in CCA NCA; do
    printf "\n$cell_type LFC > 0:\n"
    rm -f peak-indexes.txt
    for time_interval in 2-vs-0 6-vs-0 6-vs-2; do
	awk '$3 > 0 && $7 < 0.05 { print $1 }' $cell_type-day-$time_interval \
	    >> peak-indexes.txt
    done
    printf "Sum across time intervals: "
    cat peak-indexes.txt | wc -l
    printf "Unique peaks:              "
    sort peak-indexes.txt | uniq | wc -l

    printf "\n$cell_type LFC < 0:\n"
    rm -f peak-indexes.txt
    for time_interval in 2-vs-0 6-vs-0 6-vs-2; do
	awk '$3 < 0 && $7 < 0.05 { print $1 }' $cell_type-day-$time_interval \
	    >> peak-indexes.txt
    done
    printf "Sum across time intervals: "
    cat peak-indexes.txt | wc -l
    printf "Unique peaks:              "
    sort peak-indexes.txt | uniq | wc -l
done
