#!/bin/sh -e

gff=Mus_musculus.GRCm38.100.gff3.gz
if [ ! -e $gff ]; then
    for prog in fetch curl wget; do
	if which $fetch; then
	    fetch=$prog
	    break
	fi
    done
    if [ 0$fetch = 0 ]; then
	printf "No fetch program found (tried fetch, curl, wget).\n"
	exit 1
    fi
    if [ $fetch = curl ]; then
	fetch="$fetch -O"
    fi
    $fetch ftp://ftp.ensembl.org/pub/release-100/gff3/mus_musculus/$gff
fi

# Convert DESeq2 output to BED format
for file in 10-diff-anal/*CA-T*.tsv; do
    echo $file
    bed_file=${file%.tsv}.bed
    fgrep -v baseMean $file | tr '"' ' ' | \
	awk '{
	    split($1, a, "-");
	    printf("%s\t%s\t%s\t%s\n", substr(a[1],4,1),a[2],a[3],$1);
	}' > $bed_file
    head -3 $bed_file
    
    # https://bedtools.readthedocs.io/en/latest/content/tools/intersect.html
    bedtools intersect -a $gff -b $bed_file > $bed_file.intersect
done
