
# This has been replaced by 9-process-peaks.sbatch

# Process MACS2 peaks to peaklets
if ( process_peaks_in_R )
{
    # FIXME: Respect pre_merge setting
    library(GenomicRanges)
    
    macsBed <- read.delim(paste0("../7-macs-peaklets/ATAC-", cell_type,
	"-macs.peaklets_peaks.narrowPeak"), header=FALSE)
    ## Sort by p-value ($V8), only keep those with p-value < 10^-10 [44429]
    # keep - index vector
    # Done using awk
    
    # V8 = p-value.  Could use q-value as well.
    rows_to_keep <- which(macsBed$V8 > -log(10^-10))
    #print("keep (rows where p < 10^-10)")
    #print(rows_to_keep)
    
    # new table, keep rows in "keep"
    macs_pval_ok <- macsBed[rows_to_keep,]
    print("macs_pval_ok (peaks with p < 10^-10)")
    print(macs_pval_ok)
    
    # debug: How many rows were filtered out?
    cat(nrow(macsBed), "...", nrow(macs_pval_ok), "\n")
    
    ## And write out merged : AR modified to use 501 bp regions
    # like bedtools - make peaklet around summit
    # col 2 = start, col 10 = distance from start to peak
    macs_pval_ok_GR <- GRanges(seqnames=as.vector(macs_pval_ok[,1]),
			   IRanges(start=as.numeric(as.vector(macs_pval_ok[,2])) + 
				   as.numeric(as.vector(macs_pval_ok[,10])) - 250,
				   end=as.numeric(as.vector(macs_pval_ok[,2])) + 
				   as.numeric(as.vector(macs_pval_ok[,10])) + 250),
				   strand=rep("*", nrow(macs_pval_ok)))
    print("macs_pval_ok_GR: 501 nt generated peaks")
    print(macs_pval_ok_GR)
    
    # line <- readline(prompt="Press [enter] to continue")
    pause()
    
    # add metadata to table
    # Remove columns 1-3
    elementMetadata(macs_pval_ok_GR) <- macs_pval_ok[,-c(1:3)]
    
    # Add names for each col
    colnames(elementMetadata(macs_pval_ok_GR)) <- c("Peak_ID","Score","Strand", 
						"Fold-change", "log10pvalue",
						"log10qvalue",
						"Relative_summit")
    
    ## Note: we have a very small number (~50) of overlapping peaklets, I have just left
    ## them as is without merging (so we may be double counting a small number of reads)
    
    # merge overlapping peaks
    # Done with bedtools merge otherwise
    macsGR_bed <- data.frame(chr=seqnames(macs_pval_ok_GR),
			     starts=start(macs_pval_ok_GR),
			     end=end(macs_pval_ok_GR),
			     #names=c(rep(".", length(macs_pval_ok_GR))),
			     names=paste0("chr",seqnames(macs_pval_ok_GR),
					  "-", start(macs_pval_ok_GR),
					  "-", end(macs_pval_ok_GR)),
			     scores=c(rep(".", length(macs_pval_ok_GR))),
			     strands=strand(macs_pval_ok_GR))
    
    ## Note: some of the peaks need to be recentered (negative start)
    print(macsGR_bed)
    index <- which(macsGR_bed$starts < 1)
    macsGR_bed[index, "end"] <- macsGR_bed[index, "end"] - 
	macsGR_bed[index, "starts"] + 1
    macsGR_bed[index, "starts"] <- 1
    ## Note: some of the peaks need to be recentered (too long)
    # This look useless for CNC-EMDiff.  What was it for in OpticRegen?
    #index <- which(macsGR_bed$chr == "KN149934.1" & macsGR_bed$end == 12555)
    #macsGR_bed[index, "end"] <- 12451; macsGR_bed[index, "starts"] <- macsGR_bed[index, "end"] - 499
    #index <- which(macsGR_bed$chr == "KN149962.1" & macsGR_bed$end == 136196)
    #macsGR_bed[index, "end"] <- 136181; macsGR_bed[index, "starts"] <- macsGR_bed[index, "end"] - 499
    #index <- which(macsGR_bed$chr == "KN150281.1" & macsGR_bed$end == 3781)
    #macsGR_bed[index, "end"] <- 3763; macsGR_bed[index, "starts"] <- macsGR_bed[index, "end"] - 499
    #index <- which(macsGR_bed$chr == "KN150391.1" & macsGR_bed$end == 26616)
    #macsGR_bed[index, "end"] <- 26543; macsGR_bed[index, "starts"] <- macsGR_bed[index, "end"] - 499
    #write.table(macsGR_bed, paste0("PEAKS_TRANS_PEAKLETS_ALLTIMES/",
    # "ALLMERGED_ATAC.nodup.unique.macs.peaklets_peaks.pvalsort.narrowPeak_501bp.bed")
    
    write.table(macsGR_bed, paste0(cell_type, "-R-code-merged-peaks.bed"),
		col.names=FALSE, row.names=FALSE, quote=FALSE, sep="\t")
    
    # Merged peaks generated by R code above
    Peaks <- paste0(cell_type, "-R-code-merged-peaks.bed")
    
    print("macsGR_bed: Merged peaks")
    print(macsGR_bed)
    pause()

