#!/bin/sh -e

for file in *.sam; do
    if [ ${file##*.} == bam ]; then
	sam_reader="samtools view"
    else
	sam_reader="cat"
    fi

    printf "===\n$file:\n"
    printf "Total alignments: "
    total=$($sam_reader $file | mawk '{ print $1 }' | wc -l)
    printf "$total\n"
    
    printf "Gathering unmapped read QNAMEs...\n"
    samtools view -f 0x4 $file | mawk '{ print $1 }' | sort | uniq > unmapped-qnames.txt
    wc -l unmapped-qnames.txt
    
    printf "Gathering secondary read QNAMEs...\n"
    samtools view -f 0x100 $file | mawk '{ print $1 }' | sort | uniq > secondary-qnames.txt
    wc -l secondary-qnames.txt
    
    printf "Alignments excluding unmapped and multiply mapped: "
    cat unmapped-qnames.txt secondary-qnames.txt > remove.txt
    uniquely_mapped=$($sam_reader $file | mawk '{ print $1 }' | fgrep -v -f remove.txt | wc -l)
    printf "%s (%s %%)\n" $uniquely_mapped $((uniquely_mapped * 100 / $total)) \
	| tee $file.uniquely-mapped
done
