#!/bin/sh -e

##########################################################################
#   Script description:
#       Install R packages for ATAC-Seq differential analysis
#       
#   History:
#   Date        Name        Modification
#   2020-04-07  Jason Bacon Begin
##########################################################################

usage()
{
    cat << EOM

Usage: $0 prefix cran-URL

Example: $0 /sharedapps/R https://mirror.las.iastate.edu/CRAN/

See https://cran.r-project.org/mirrors.html for mirror URLs

EOM
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 2 ]; then
    usage
fi

prefix="$1"
url="$2"

env_file=$HOME/.Renviron
profile=$HOME/.Rprofile

# FIXME: Change this to respect $prefix and $url regardless of
# .Renviron and .Rprofile
if ! fgrep -q R_LIBS_USER $env_file; then
    cat << EOM >> $env_file
R_LIBS_USER=$prefix
EOM
else
    printf "R_LIBS_USER already set.\n"
fi

if ! fgrep -q 'r["CRAN"]' $profile; then
    cat << EOM >> $profile
local({
  r <- getOption("repos")
  r["CRAN"] <- "$url"
  options(repos = r)
})
EOM
else
    printf 'r["CRAN"] already set.\n'
fi

mkdir -p $prefix

Rscript Utils/install-R-packages.R
